import "dotenv/config";

function required(name: string): string {
  const val = process.env[name];
  if (!val) throw new Error(`Missing required env var: ${name}`);
  return val;
}

// ─── Env vars ───

export const PRIVATE_KEY = required("PRIVATE_KEY");
export const ANTHROPIC_API_KEY = required("ANTHROPIC_API_KEY");

// Optional: pre-cached API creds (generated by setup-wallet script)
export const POLY_API_KEY = process.env.POLY_API_KEY || "";
export const POLY_API_SECRET = process.env.POLY_API_SECRET || "";
export const POLY_API_PASSPHRASE = process.env.POLY_API_PASSPHRASE || "";

export const DRY_RUN = process.env.DRY_RUN === "true";
export const LOG_LEVEL = process.env.LOG_LEVEL || "info";

// ─── Network ───

export const CHAIN_ID = 137; // Polygon
export const POLYGON_RPC = "https://polygon-rpc.com";
export const CLOB_API = "https://clob.polymarket.com";
export const GAMMA_API = "https://gamma-api.polymarket.com";

// ─── Contract addresses (Polygon) ───

export const USDC_ADDRESS = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"; // USDC.e on Polygon
export const CTF_EXCHANGE = "0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E";
export const NEG_RISK_CTF_EXCHANGE = "0xC5d563A36AE78145C45a50134d48A1215220f80a";
export const CONDITIONAL_TOKENS = "0x4D97DCd97eC945f40cF65F87097ACe5EA0476045";
export const NEG_RISK_ADAPTER = "0xd91E80cF2E7be2e162c6513ceD06f1dD0dA35296";

// ─── Trading params ───

export const TRADING = {
  edgeThreshold: 0.08,        // 8% minimum edge
  kellyFraction: 0.25,        // Quarter Kelly
  maxPositionPct: 0.06,       // 6% max of bankroll per trade
  maxOpenPositions: 5,
  minLiquidity: 500,          // $500 min market liquidity
  dailyApiCap: 1.0,           // $1.00 max daily API cost
  minTradeSize: 0.50,         // $0.50 minimum
  maxTradesPerCycle: 2,
  cycleIntervalMs: 10 * 60 * 1000,  // 10 minutes
  initialBankroll: 20,        // $20 starting
} as const;

// ─── Estimation params ───

export const ESTIMATION = {
  batchSize: 50,              // markets per Stage 1 batch
  stage1Model: "claude-haiku-4-5-20251001" as const,
  stage2Model: "claude-haiku-4-5-20251001" as const,
  stage1PotentialEdge: 0.06,  // 6% potential edge to advance to Stage 2
  stage2MinConfidence: 0.50,  // 50% confidence to become a signal
  maxStage2Candidates: 15,
} as const;

// ─── State file paths ───

import path from "path";

export const STATE_DIR = path.join(__dirname, "..", "..", "state");
export const STATE_FILE = path.join(STATE_DIR, "agent-state.json");
export const CREDS_FILE = path.join(STATE_DIR, "api-creds.json");
