import "dotenv/config";

function required(name: string): string {
  const val = process.env[name];
  if (!val) throw new Error(`Missing required env var: ${name}`);
  return val;
}

// ─── Env vars ───

export const PRIVATE_KEY = process.env.PRIVATE_KEY || "";
export const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY || "";

// Optional: pre-cached API creds (generated by setup-wallet script)
export const POLY_API_KEY = process.env.POLY_API_KEY || "";
export const POLY_API_SECRET = process.env.POLY_API_SECRET || "";
export const POLY_API_PASSPHRASE = process.env.POLY_API_PASSPHRASE || "";

export const DRY_RUN = process.env.DRY_RUN === "true";
export const LOG_LEVEL = process.env.LOG_LEVEL || "info";

// ─── Network ───

export const CHAIN_ID = 137; // Polygon
export const POLYGON_RPC = "https://polygon-rpc.com";
export const CLOB_API = "https://clob.polymarket.com";
export const GAMMA_API = "https://gamma-api.polymarket.com";

// ─── Contract addresses (Polygon) ───

export const USDC_ADDRESS = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"; // USDC.e on Polygon
export const CTF_EXCHANGE = "0x4bFb41d5B3570DeFd03C39a9A4D8dE6Bd8B8982E";
export const NEG_RISK_CTF_EXCHANGE = "0xC5d563A36AE78145C45a50134d48A1215220f80a";
export const CONDITIONAL_TOKENS = "0x4D97DCd97eC945f40cF65F87097ACe5EA0476045";
export const NEG_RISK_ADAPTER = "0xd91E80cF2E7be2e162c6513ceD06f1dD0dA35296";

// ─── Trading params ───

export const TRADING = {
  edgeThreshold: 0.03,        // 3% minimum edge - stricter after learning
  kellyFraction: 0.25,        // 25% Kelly - more conservative after losses
  maxPositionPct: 0.25,       // 25% max of bankroll per trade
  maxOpenPositions: 15,       // More slots since they resolve fast
  minLiquidity: 100,          // $100 min - more opportunities
  dailyApiCap: 100.00,          // Much higher cap
  minTradeSize: 1.00,         // $1 minimum
  maxTradesPerCycle: 10,       // More trades per cycle
  maxDaysToResolution: 14,     // Markets resolving within 14 days
  cycleIntervalMs: 30 * 60 * 1000,  // 30 minutes
  initialBankroll: 1000,      // $1000 starting
  maxTradeRisk: 0.10,        // 10% max bankroll risk per trade
  midPriceEdgePenalty: 1.5,   // 50% more edge required for 40-60¢ markets
  minPriceThreshold: 0.10,    // Skip markets below 10 cents (longshot trap)
} as const;

// ─── Estimation params ───

export const ESTIMATION = {
  batchSize: 5,               // smaller batches for free-tier reliability
  // Stage 1 fallback chain: try each model in order until one succeeds
  stage1Models: [
    "google/gemma-3-27b-it:free",
    "nousresearch/hermes-3-llama-3.1-405b:free",
    "deepseek/deepseek-r1-0528:free",
  ] as readonly string[],
  stage1Model: "google/gemma-3-27b-it:free",  // legacy field (used as default)
  stage2Model: "stepfun/step-3.5-flash:free",  // default fallback
  stage1PotentialEdge: 0.03,  // 3% potential edge to advance to Stage 2 (stricter)
  stage2MinConfidence: 0.50,  // 50% min confidence - reduced overconfidence
  maxStage2Candidates: 8,     // Keep low for free tier (8 × 3 models = 24 calls)
  // 3 free models compete independently + ensemble consensus
  ensembleModels: [
    "deepseek/deepseek-r1-0528:free",
    "google/gemma-3-27b-it:free",
    "nousresearch/hermes-3-llama-3.1-405b:free",
  ],
} as const;

// ─── Calibration ───
// Shrinkage pulls our estimate toward the market price to reduce overconfidence.
// Less shrinkage = more aggressive trading

export const CALIBRATION = {
  shrinkageFactor: 0.50,  // Trust only 50% of our edge - more conservative after losses
} as const;

// ─── Web research ───
// Before Stage 2, search the web for real-time context (weather forecasts,
// team lineups, recent news) so Claude isn't estimating from stale priors.
export const RESEARCH = {
  enabled: false,
  maxSearchesPerCycle: 0,
  model: "stepfun/step-3.5-flash:free",
  maxSearchUses: 0,
} as const;

// ─── Market category preferences ───
// Multiplier applied to edge for threshold check.
// >1.0 = lower bar (Claude has an edge here), <1.0 = higher bar (Claude is disadvantaged).

export const CATEGORY_MULTIPLIERS: Record<string, number> = {
  speech: 1.5,
  political: 1.4,
  niche: 1.3,
  financial: 1.2,
  sports: 1.1,
  crypto: 1.0,
  esports: 1.0,
  weather: 1.0,
};

// ─── State file paths ───

import path from "path";

export const STATE_DIR = path.join(__dirname, "..", "..", "state");
export const STATE_FILE = path.join(STATE_DIR, "agent-state.json");
export const CREDS_FILE = path.join(STATE_DIR, "api-creds.json");
